// ReSharper disable UnusedParameter.Local

namespace Xylib;

/// <summary>
///     Marks the feature supported by a patch.
/// </summary>
/// <remarks>
///     <para>
///         This attribute is only for documentation and searchability; it has no runtime effect.
///     </para>
///     <para>
///         Prefer <see langword="typeof" /> or <see langword="nameof" /> over a bare string when passing the feature name.
///     </para>
/// </remarks>
/// <param name="featureName">
///     The name of the feature supported by the patch.
/// </param>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class FeatureAttribute(string featureName) : Attribute
{
    // ReSharper disable once UnusedMember.Global
    /// <summary>
    ///    The name of the feature supported by the patch.
    /// </summary>
    public readonly string featureName = featureName;

    /// <summary>
    ///     Marks a patch as supporting the feature implemented by the specified type.
    /// </summary>
    /// <param name="feature">
    ///     The type that implements the supported feature.
    /// </param>
    public FeatureAttribute(Type feature) : this(feature.Name)
    {
    }
}

/// <summary>
///     Documents that a class is referenced by name from XML.
/// </summary>
/// <remarks>
///     This attribute has no runtime effect.
/// </remarks>
[MeansImplicitUse]
[AttributeUsage(AttributeTargets.Class)]
public class UsedFromXmlAttribute : Attribute;

/// <summary>
///     Documents that a class, method, property, or field is loaded through reflection.
/// </summary>
/// <remarks>
///     This attribute has no runtime effect.
/// </remarks>
[MeansImplicitUse]
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field)]
public class UsedFromReflectionAttribute : Attribute;

/// <summary>
///     Marks a class as a def generator.
/// </summary>
/// <remarks>
///     The library looks for a static method named <c>ImpliedDefs</c> that takes a <see cref="bool" /> and returns a value convertible
///     to <see cref="IEnumerable{T}" />, where <c><see langword="typeof"/>(T)</c> matches <paramref name="defType" />. It runs the method after the base
///     game def generators run, then adds the returned defs to <see cref="DefDatabase{T}" />.
/// </remarks>
/// <param name="defType">
///     The <see cref="Def" /> subclass generated by <c>ImpliedDefs</c>, such as <see cref="ThingDef" /> or <see cref="GeneDef" />.
/// </param>
/// <example>
/// <code>
/// [DefGenerator(typeof(GeneDef))]
/// public static class GeneDefGenerator
/// {
///     public static IEnumerable&lt;GeneDef&gt; ImpliedDefs(bool hotReload) => [];
/// }
/// </code>
/// </example>
[MeansImplicitUse]
[AttributeUsage(AttributeTargets.Class)]
public class DefGeneratorAttribute(Type defType) : Attribute
{
    /// <summary>
    ///     The <see cref="Def"/> subtype which this generator produces.
    /// </summary>
    public readonly Type defType = defType;
}

/// <summary>
///     Provides a custom XML tag to use when saving/loading this class in <see cref="PawnExtraData{T}" />.
/// </summary>
/// <remarks>
///     Without this attribute, the XML tag is the class name including namespace.
/// </remarks>
/// <param name="label">The tag to use.</param>
[AttributeUsage(AttributeTargets.Class)]
public class ScribeLabelAttribute(string label) : Attribute
{
    /// <summary>
    ///     The XML tag to use when saving/loading this class in <see cref="PawnExtraData{T}" />.
    /// </summary>
    public readonly string label = label;
}