<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Xylib</AssemblyName>
    <RootNamespace>Xylib</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source_Disharmony\Source_Disharmony.csproj" />
  </ItemGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;bin\$(Configuration)\net4.7.2\Xylib.dll&quot; &quot;..\XylXenos\Assemblies\Xylib.dll&quot;" />
  </Target>

</Project>
