<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AssemblyName>XylXenos</AssemblyName>
    <RootNamespace>XylXenos</RootNamespace>

    <Version>1.0.0.0</Version>
    <AssemblyInformationalVersion>1.0.0-alpha</AssemblyInformationalVersion>

    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizerLogFilePath>../Build/Publicizer.log.txt</PublicizerLogFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp:RimWorld.GameConditionManager.AllowEnjoyableOutsideNow" />
    <Publicize Include="Assembly-CSharp:RimWorld.Pawn_FlightTracker.flightCooldownTicks" />
    <Publicize Include="Assembly-CSharp:RimWorld.XenotypeSet.xenotypeChances" />
    <Publicize Include="Assembly-CSharp:Verse.HediffComp_TendDuration.totalTendQuality" />
    <Publicize Include="Assembly-CSharp:Verse.ShotReport.factorFromCoveringGas" />
    <Publicize Include="Assembly-CSharp:Verse.XmlToObjectUtils.customDataLoadMethodCache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source_Xylib\Source_Xylib.csproj" />
    <ProjectReference Include="..\Source_Disharmony\Disharmony.csproj" />
    <ProjectReference Include="..\Source_Disharmony.Analyzers\Disharmony.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll&quot; &quot;..\XylXenos\Assemblies\XylXenos.dll&quot;" />
  </Target>

</Project>
