<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>XylIdeos</AssemblyName>
    <RootNamespace>XylIdeos</RootNamespace>
  </PropertyGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;bin\$(Configuration)\net4.7.2\XylIdeos.dll&quot; &quot;..\XylIdeoTweaks\Assemblies\XylIdeos.dll&quot;" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source_Xylib\Source_Xylib.csproj" />
    <ProjectReference Include="..\Source_Disharmony\Source_Disharmony.csproj" />
    <ProjectReference Include="..\Source_Disharmony.Analyzers\Source_Disharmony.Analyzers.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
