<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>XylIdeos</AssemblyName>
    <RootNamespace>XylIdeos</RootNamespace>
  </PropertyGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath);$(TargetDir)0Harmony.dll;$(TargetDir)Disharmony.dll;$(TargetDir)Disharmony.RimWorld.dll" DestinationFolder="$(MSBuildProjectDirectory)\..\ModBin\XylIdeos\Assemblies" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XylIdeos.Data\XylIdeos.Data.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Xylib\Xylib.csproj" />
    <ProjectReference Include="..\..\Disharmony\Disharmony\Disharmony.csproj" />
    <ProjectReference Include="..\..\Disharmony\Disharmony.RimWorld\Disharmony.RimWorld.csproj" />
    <ProjectReference Include="..\..\Disharmony\Disharmony.Analyzers\Disharmony.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
