<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>Disharmony.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source_Disharmony\Source_Disharmony.csproj" />
    <ProjectReference Include="..\Source_Disharmony.TestTargets\Source_Disharmony.TestTargets.csproj">
      <SetConfiguration>Configuration=Release</SetConfiguration>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
