<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath>..\Build\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <IntermediateOutputPath>..\Build\obj\$(MSBuildProjectName)\</IntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="@(None)" DestinationFiles="@(None->'$(MSBuildProjectDirectory)\..\ModBin\XylIdeos\%(Identity)')" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CleanModOutput" AfterTargets="Clean">
    <RemoveDir Directories="$(MSBuildProjectDirectory)\..\ModBin\XylIdeos" />
  </Target>
</Project>