<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.7.2</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>XylSavePatched</AssemblyName>
    <RootNamespace>XylSavePatched</RootNamespace>

    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizerLogFilePath>../Build/Publicizer_SavePatched.log.txt</PublicizerLogFilePath>
  </PropertyGroup>

  <Target Name="Postbuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll&quot; &quot;..\XylSavePatched\Assemblies\XylSavePatched.dll&quot;" />
    <Exec Command="copy &quot;bin\$(Configuration)\$(TargetFramework)\XylDisassembler.dll&quot; &quot;..\XylSavePatched\Assemblies\XylDisassembler.dll&quot;" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="0Harmony:HarmonyLib.PatchFunctions.GetSortedPatchMethods" />
    <Publicize Include="0Harmony:HarmonyLib.MethodPatcher" />
    <Publicize Include="0Harmony:HarmonyLib.MethodPatcher..ctor" />
    <Publicize Include="0Harmony:HarmonyLib.MethodPatcher.CreateReplacement" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source_Disassembler\Source_Disassembler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>